name: go-release

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
          cache: true

      - name: run tests
        run: |
          go test ./... -v
          go vet ./...
          go fmt ./...
          golint ./...
